source "$HOME/.cargo/env"

export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

export HOMEBREW_PREFIX="/opt/homebrew"
export HOMEBREW_CELLAR="/opt/homebrew/Cellar"
export HOMEBREW_REPOSITORY="/opt/homebrew"
export HOMEBREW_SHELLENV_PREFIX="/opt"

export MANPATH="/opt/homebrew/share/man:$MANPATH"
export INFOPATH="/opt/homebrew/share/info:$INFOPATH"

export BOOST_ROOT=/opt/homebrew/opt/boost

export ANDROID_HOME="$HOME/Library/Android/sdk"

export JAVA_HOME="$(/usr/libexec/java_home)"

# lukechilds/zsh-nvm
export NVM_LAZY_LOAD=true
