add_newline = true
command_timeout = 1750

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$line_break\
$jobs\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = false
read_only = " \U000f033e"

[git_branch]
format = "[$symbol $branch(:$remote_branch)]($style) "
symbol = "\uf418"

[git_status]
format = "[$all_status$ahead_behind]($style)"

[cmd_duration]
format = " [$duration]($style)"

[python]
format = "[(${symbol}  $virtualenv)]($style)"
symbol = "\ue606"
